config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :orders
  resources :messages
  resources :product_categories
  resources :reviews
  resources :address_types
  resources :addresses
  resources :notifications
  resources :roles
  resources :bids
  resources :products
  resources :customers
  resources :stores
  devise_for :users
  get 'heaven/index'
  get 'heaven/show_user'
  post 'bids/bid_create'
  post 'bids/delete_bid'
  # root to: "heaven#index"
  # get heaven/index"
  root to: "heaven#home"
  post 'heaven/create_review'
  post 'heaven/create_product_review'
  get 'heaven/products'
  get 'heaven/messages'
  get 'heaven/notification_toggle'
end

app/controllers/address_types_controller.rb
class AddressTypesController < ApplicationController
  before_action :set_address_type, only: %i[ show edit update destroy ]

  # GET /address_types or /address_types.json
  def index
    @address_types = AddressType.all
  end

  # GET /address_types/1 or /address_types/1.json
  def show
  end

  # GET /address_types/new
  def new
    @address_type = AddressType.new
  end

  # GET /address_types/1/edit
  def edit
  end

  # POST /address_types or /address_types.json
  def create
    @address_type = AddressType.new(address_type_params)

    respond_to do |format|
      if @address_type.save
        format.html { redirect_to address_type_url(@address_type), notice: "Address type was successfully created." }
        format.json { render :show, status: :created, location: @address_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /address_types/1 or /address_types/1.json
  def update
    respond_to do |format|
      if @address_type.update(address_type_params)
        format.html { redirect_to address_type_url(@address_type), notice: "Address type was successfully updated." }
        format.json { render :show, status: :ok, location: @address_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /address_types/1 or /address_types/1.json
  def destroy
    @address_type.destroy

    respond_to do |format|
      format.html { redirect_to address_types_url, notice: "Address type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address_type
      @address_type = AddressType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_type_params
      params.require(:address_type).permit(:address_type)
    end
end

app/views/address_types/_form.html.erb
<%= form_with(model: address_type, local: true) do |form| %>
  <% if address_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address_type.errors.count, "error") %> prohibited this address_type from being saved:</h2>

      <ul>
      <% address_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address_type %>
    <%= form.text_field :address_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/address_types/edit.html.erb
<h1>Editing Address Type</h1>

<%= render 'form', address_type: @address_type %>

<%= link_to 'Show', @address_type %> |
<%= link_to 'Back', address_types_path %>

app/views/address_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Address Types</h1>

<table>
  <thead>
    <tr>
      <th>Address type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @address_types.each do |address_type| %>
      <tr>
        <td><%= address_type.address_type %></td>
        <td><%= link_to 'Show', address_type %></td>
        <td><%= link_to 'Edit', edit_address_type_path(address_type) %></td>
        <td><%= link_to 'Destroy', address_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address Type', new_address_type_path %>

app/views/address_types/new.html.erb
<h1>New Address Type</h1>

<%= render 'form', address_type: @address_type %>

<%= link_to 'Back', address_types_path %>

app/views/address_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address type:</strong>
  <%= @address_type.address_type %>
</p>

<%= link_to 'Edit', edit_address_type_path(@address_type) %> |
<%= link_to 'Back', address_types_path %>