config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :orders
  resources :messages
  resources :product_categories
  resources :reviews
  resources :address_types
  resources :addresses
  resources :notifications
  resources :roles
  resources :bids
  resources :products
  resources :customers
  resources :stores
  devise_for :users
  get 'heaven/index'
  get 'heaven/show_user'
  post 'bids/bid_create'
  post 'bids/delete_bid'
  # root to: "heaven#index"
  # get heaven/index"
  root to: "heaven#home"
  post 'heaven/create_review'
  post 'heaven/create_product_review'
  get 'heaven/products'
  get 'heaven/messages'
  get 'heaven/notification_toggle'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :bids

  before_update :check_product_edited

  private
  def check_product_edited
    puts "\n\n\n check before update\n\n\n\n"
    puts self.inspect
    create_new_message(self.user_id, "product updated and the url is <a href='/products/#{self.id}' > click here </a>")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :check_role#, except: [:show]

  # GET /products or /products.json
  def index
    @products = Product.all
    puts @products.to_json
  end

  # GET /products/1 or /products/1.json
  def show

    @bid = Bid.new
    puts "\n\nproduct is #{@product} \n\n"
    # debugger
    puts "\n\n end\n\n"
    @bids = @product.bids
    @reviews = Review.where(:product_id => @product.id)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :barcode, :user_id, :bid_enable, :bid_status, :price, :bid_timer)
  end
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :barcode %>
    <%= form.number_field :barcode %>
  </div>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>
  <div class="field">
    <%= form.label :bid_enable %>
    <%= form.check_box :bid_enable %>
  </div>
  <div class="field">
    <%= form.label :bid_status %>
    <%# form.text_field :bid_status %>
    <%= form.select :bid_status, ["open", "closed"]%>
  </div>
  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <div class="field">
    <%= form.label :bid_timer %>
    <%= form.datetime_select :bid_timer %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Barcode</th>
      <th>User</th>
      <th>Bid enable</th>
      <th>Bid status</th>
      <th>Bid timer</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.barcode %></td>
        <td><%= product.user_id %></td>
        <td><%= product.bid_enable %></td>
        <td><%= product.bid_status %></td>
        <td><%= product.bid_timer %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
<p>
  <strong>Barcode:</strong>
  <%= @product.barcode %>
</p>
<p>
  <strong>User:</strong>
  <%= @product.user_id %>
</p>
<p>
  <strong>Bid enable:</strong>
  <%= @product.bid_enable %>
</p>
<p>
  <strong>Bid status:</strong>
  <%= @product.bid_status %>
</p>
<p>
  <strong>Bid Timer:</strong>
  <% if(@product.bid_timer) %>
    <% sec = (((@product.bid_timer - DateTime.now)* 24 * 60 * 60).to_i)/(24*60*60).to_i %>
    <% if(sec > 0) %>
      <%= [sec / 3600, sec / 60 % 60, sec % 60].map{|t| t.to_s.rjust(2,'0')}.join(':') %> time Left
    <% else %>
      <span style="color: red">Sold Out</span>
    <% end %>
  <% else %>
    Open for Bidding
  <% end %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<br>
<br>
<hr>
<br>
<h2> Bid Section</h2>
<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>User</th>
      <th>Bid price</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @bids.each do |bid| %>
      <tr>
        <td><%= bid.product_id %></td>
        <td><%= bid.user_id %></td>
        <td><%= bid.bid_price %></td>
        <td><%= link_to 'Show', bid %></td>
        <td>
          <% if bid.user_id == current_user.id %>
            <%= link_to 'Edit', edit_bid_path(bid) %>
          <% end %>
        </td>
        <td>
          <% if bid.user_id == current_user.id %>
            <% link_to 'Destroy', bid, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%= link_to 'Delete', bids_delete_bid_path(id: bid), method: :post, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if @bids.where(:user_id => current_user.id).count > 0 %>
  <h1> Already bid for this product </h1>
<% else %>
  <%# link_to 'New Bid', new_bid_path %>
  <% if(@product.bid_timer) %>
    <% sec = (((@product.bid_timer - DateTime.now)* 24 * 60 * 60).to_i)/(24*60*60).to_i %>
    <% if(sec > 0) %>
      <%= [sec / 3600, sec / 60 % 60, sec % 60].map{|t| t.to_s.rjust(2,'0')}.join(':') %> time Left
      <%= form_with model: @bid,url: "/bids/bid_create", :method => 'post' do |form| %>
        <div class="field">
          <%= form.label :product_id %>
          <%= form.number_field :product_id, :value =>  @product.id%>
        </div>
        <div class="field">
          <%= form.label :user_id %>
          <%= form.number_field :user_id, :value => current_user.id %>
        </div>
        <div class="field">
          <%= form.label :bid_price %>
          <%= form.text_field :bid_price %>
        </div>
        <div class="actions">
          <%= form.submit "Place Bid" %>
        </div>
      <% end %>
    <% else %>
      <span style="color: red">Sold Out</span>
    <% end %>
  <% else %>
  <% end %>
<% end %>
<br>
<br>
<hr>
<br>
<h2>Review Section</h2>
<% if @reviews.count > 0 %>
  <table>
    <thead>
      <tr>
        <!-- <th>User</th> -->
        <th>Message</th>
        <th>Rating</th>
      </tr>
    </thead>
    <tbody>
      <% @reviews.each do |review| %>
        <tr>
          <!-- <td><%# review.user_id %></td> -->
          <td><%= review.message %></td>
          <td><%= review.rating %></td>
          <td><%= link_to 'Show', review %></td>
          <td>
            <% if current_user.id == review.from_user_id %>
              <%= link_to 'Edit', edit_review_path(review) %>
            <% end %>
          </td>
          <td>
            <% if current_user.id == review.from_user_id %>
              <% link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %>
              <%= link_to 'Delete', review_path(id: review), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <h1>No Reviews </h1>
<% end %>
<% if @reviews.count > 0 %>
  <h1> Already Reviewed! </h1>
<% else %>
  Please write a Review about the product 
  <h1><%= @product.name %></h1>
  <%# link_to 'New Review', new_bid_path %>
  <%= form_with model: @review,url: "/heaven/create_product_review", :method => 'post' do |form| %>
    <div class="field">
      <%# form.label :user_id %>
      <%= form.hidden_field :product_id, :value =>  @product.id%>
    </div>
    <div class="field">
      <%= form.label :message %>
      <%= form.text_field :message %>
    </div>
    <div class="field">
      <%= form.label :rating %>
      <%= form.select :rating, [1,2,3,4,5]%>
    </div>
    <div class="actions">
      <%= form.submit "Submit" %>
    </div>
  <% end %>
<% end %>